cleanup dockerfile to match others

diff --git a/stride/Dockerfile b/stride/Dockerfile
--- a/stride/Dockerfile
+++ b/stride/Dockerfile
@@ -4,55 +4,54 @@ ARG arch=x86_64
 ENV STRIDE_VERSION=v12.1.0
 ENV PACKAGES git cmake ca-certificates build-base curl make libc-dev bash gcc linux-headers eudev-dev python3 libusb-dev
 
-RUN set -eux; apk add --no-cache $PACKAGES;
+RUN set -eux; \
+    apk add --no-cache $PACKAGES
 
 WORKDIR /code
 
-# Install mimalloc
-RUN git clone --depth 1 https://github.com/microsoft/mimalloc; cd mimalloc; mkdir build; cd build; cmake ..; make -j$(nproc); make install
+# Install mimalloc static library and cleanup
+RUN git clone --depth 1 https://github.com/microsoft/mimalloc; \
+    cd mimalloc; \
+    mkdir build; \
+    cd build; \
+    cmake -DMI_INSTALL_TOPLEVEL=ON -DBUILD_SHARED_LIBS=OFF ..; \
+    make -j$(nproc); \
+    make install; \
+    cd /code; \
+    rm -rf mimalloc
 
-# Download Gaia
-RUN git clone https://github.com/Stride-Labs/stride
-WORKDIR /code/stride
-RUN git checkout ${STRIDE_VERSION}
 
-# force it to use static lib (from above) not standard libgo_cosmwasm.so file
-RUN LEDGER_ENABLED=false BUILD_TAGS="muslc badgerdb" LDFLAGS="-linkmode=external -extldflags \"-L/code/mimalloc/build -lmimalloc -Wl,-z,muldefs -static\"" make install
+# Download stride and build
+ADD https://github.com/Stride-Labs/stride/archive/refs/tags/${STRIDE_VERSION}.tar.gz ${STRIDE_VERSION}.tar.gz
+RUN tar -xzf ${STRIDE_VERSION}.tar.gz && \
+    cd stride-${STRIDE_VERSION#v} && \
+    LEDGER_ENABLED=false BUILD_TAGS="muslc badgerdb" LDFLAGS="-linkmode=external -extldflags \"-L/code/mimalloc/build -lmimalloc -Wl,-z,muldefs -static\"" make install
 
-
-FROM alpine
+# Stage 2: Create minimal runtime image
+FROM alpine:3
 
 ENV DAEMON_NAME="strided"
 ENV DAEMON_HOME="/stride/.stride"
 
-RUN apk add --no-cache lz4 tar gettext
+RUN apk add --no-cache lz4 tar gettext && \
+    addgroup -g 1211 stride && \
+    adduser -G stride -u 1210 -D -h /stride stride && \
+    mkdir -p /stride/.stride/config /stride/.stride/data && \
+    chown stride:stride -R /stride
 
-RUN addgroup -g 1211 stride \
-    && adduser -G stride -u 1210 -D -h /stride stride
 
 COPY ./config /stride/config-sample
 COPY ./entrypoint.sh /stride
 
-RUN chown stride:stride -R /stride/config-sample
-RUN chown stride:stride /stride/entrypoint.sh
-RUN chmod +x /stride/entrypoint.sh
+RUN chown stride:stride /stride/entrypoint.sh && \
+    chmod +x /stride/entrypoint.sh
 
 USER stride
-
 WORKDIR /stride
-
-RUN mkdir -p .stride/config; mkdir -p .stride/data;
 
 COPY --from=go-builder /go/bin/strided /usr/local/bin/strided
 
-
-# rest server
-EXPOSE 1317
-# grpc
-EXPOSE 9090
-# tendermint p2p
-EXPOSE 26656
-# tendermint rpc
-EXPOSE 26657
+# rest, grpc, p2p, rpc
+EXPOSE 1317 9090 26656 26657
 
 CMD ["sh", "-c", "/stride/entrypoint.sh"]
